xfw {
    # There are two actions - block and ratelimit - it's undefined what
    # the filter must do
    # We also have to use existing rate limits. They must be defined either in
    # the current update or in one of the previous ones, and must not have been
    # deleted since then.
    src=my_white_list1 ip6.udp : block ratelimit=whitelist_ratelimit
    {
        1001:0db8:85a3:0000:0000:8a2e:0370:7334/100,
        2001:0db8:85a3:0000:0000:8a2e:0370:7334/110,
    }

    # This sections intersects with the previous one since both of them
    # have the same name
    src=my_white_list1/add ip6.udp {
        3001:db8:85a3::8a2e:370:7334/120,
        4001:0db8:85a3:0000:0000:8a2e:0370:7334/90
    }

    # '/add' or '/del' edits should not contain
    # action specification (allow, block, ratelimit)
    src=section_from_previous/add ip4.udp : allow {
        :5353
    }

    # It is not good to have unused ratelimits.
    ratelimit=default_ratelimit pps=5 bps=30000;

    # Dst ip address always has to have port.
    dst=foo ip4.udp {
        1.1.1.1:8001,
        127.0.0.1
    }

    # `dst` may either be `in` or `out`.
    dst=bad out ip6.tcp {}

    # It's not OK to have the same name for different sections.
    src=my_white_list1 ip4.udp : allow {}
}
