# See comments for the config at https://tempesta-tech.com/tempesta-escudo/knowledge-base/Web-server/

xfw {
	#evaluation_mode;
	tcp_anomaly_filter;
	tcp_syncookies passive_timer=1 flood_timer=1;

	ratelimit=http_rl bps=131072 pps=1000;
	dst=http4 ip4.tcp : ratelimit=http_rl {
		192.168.100.4:80,
		192.168.100.4:443
	}
	dst=http6 ip6.tcp : ratelimit=http_rl {
		[::192.168.100.4]:80,
		[::192.168.100.4]:443
	}
	dst=quic4 ip4.udp : ratelimit=http_rl {
		192.168.100.4:443
	}
	dst=quic6 ip6.udp : ratelimit=http_rl {
		[::192.168.100.4]:443
	}

	ratelimit=ssh_rl bps=50000 pps=500;
	dst=ssh ip4.tcp : ratelimit=ssh_rl {
		192.168.100.4:22
	}

	ratelimit=icmp_rl bps=1000 pps=10;
	icmp ip4 : ratelimit=icmp_rl { 0, 3, 8, 11, 12 }
	icmp ip6 : ratelimit=icmp_rl { 1, 2, 3, 4, 128, 129, 133, 134, 135, 136 }

	defaults {
		dst: allow;
		icmp ip4: block;
		icmp ip6: block;
	}
}
