# See comments for the config at https://tempesta-tech.com/tempesta-escudo/knowledge-base/DNS-server/

xfw {
	#evaluation_mode;
	tcp_anomaly_filter;

	dns_filter;

	ratelimit=tcp_flood_rl bps=10000000 pps=1000;
	tcp_flags syn : ratelimit=tcp_flood_rl;
	tcp_flags rst : ratelimit=tcp_flood_rl;

	ratelimit=dns_auth_ammpl_rl bps=1000000 pps=100;
	src=dns_auth_ammpl ip4.udp : ratelimit=dns_auth_ammpl_rl {
		:53
	}

	ratelimit=dns_clnt_rl bps=10000 pps=10;
	dst=dns4 ip4.udp : ratelimit=dns_clnt_rl {
		8.8.8.8:53
	}
	dst=dns6 ip6.udp : ratelimit=dns_clnt_rl {
		[::8.8.8.8]:53
	}

	ratelimit=ssh_rl bps=50000 pps=500;
	dst=ssh ip4.tcp : ratelimit=ssh_rl {
		192.168.100.4:22
	}

	ratelimit=icmp_rl bps=1000 pps=10;
	icmp ip4 : ratelimit=icmp_rl { 0, 3, 8, 11, 12 }
	icmp ip6 : ratelimit=icmp_rl { 1, 2, 3, 4, 128, 129, 133, 134, 135, 136 }

	defaults {
		dst: allow;
		src_ip: allow;
		src_port: allow;
		icmp ip4: block;
		icmp ip6: block;
	}
}
