/**
 *	Tempesta xFW egress eBPF processing
 *
 * SPDX-FileCopyrightText: © 2026 Tempesta Technologies, Inc.
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#define BPF_PROGRAM
#define XFW_TC
#define BANNER "tc"

#include "vmlinux.h"

#include "../common/bpf_uapi.h"

#ifndef TC_ACT_OK
#define TC_ACT_OK		BPF_OK
#endif

#ifndef TC_ACT_SHOT
#define TC_ACT_SHOT		BPF_DROP
#endif

#include "ctx.h"
#include "dns.h"
#include "dst.h"
#include "filter.h"
#include "log.h"
#include "parsing_helpers.h"
#include "tcp_auth.h"

/* Protected-network tries classify egress packets as internal or upstream. */
SHADOW_MAP(MAP_NET_IP4_BASENAME, BPF_MAP_TYPE_LPM_TRIE, XFW_MAX_PROTECTED_NET_RULES,
	    XfwIpv4LpmKey, int, BPF_F_NO_PREALLOC);
SHADOW_MAP(MAP_NET_IP6_BASENAME, BPF_MAP_TYPE_LPM_TRIE, XFW_MAX_PROTECTED_NET_RULES,
	    XfwIpv6LpmKey, int, BPF_F_NO_PREALLOC);

/**
 * Parsing function, should not drop packets!
 */
static __always_inline int
out_process_l3(XfwGlobalCtx *ctx, XfwDstKey *dst_key, XfwIpLpmKey* prot_net_key,
	       void **prot_net_map)
{
	switch (ctx->ipver) {
	case bpf_ntohs(ETH_P_IP): {
		REG_PACKET_GLOBAL(ctx, XFW_IP4_TOTAL_EGRESS);
		int proto = parse_iphdr(&ctx->hdr_cur, &ctx->iph4);
		if (unlikely(proto < 0))
			return XFW_MAKE_CTX_PASS(ctx, XFW_IP4_BADHDR_EGRESS);

		ctx->l4_proto = (u8)proto;
		xfw_ipv4_to_ipv6_mapped(ctx->iph4->daddr, ctx->ilog_addr.addr32);
		ipv4_populate_lpm_key(ctx->iph4->daddr, &prot_net_key->addr4);
		ipv4_populate_dst_key(ctx->iph4, ctx->l4_proto, dst_key);
		*prot_net_map = SELECT_SHADOW_MAP(MAP_NET_IP4_BASENAME,
						   ctx->cfg->amap_prot_net);
		/* It is a regular case, don't need to add any statistic */
		return XFW_CTX_CONTINUE;
	}
	case bpf_ntohs(ETH_P_IPV6): {
		REG_PACKET_GLOBAL(ctx, XFW_IP6_TOTAL_EGRESS);
		int proto = parse_ip6hdr(&ctx->hdr_cur, &ctx->iph6);
		if (unlikely(proto < 0))
			return XFW_MAKE_CTX_PASS(ctx, XFW_IP6_BADHDR_EGRESS);

		ctx->l4_proto = (u8)proto;
		ctx->ilog_addr.in6 = ctx->iph6->daddr;
		ipv6_populate_lpm_key(&ctx->iph6->daddr, &prot_net_key->addr6);
		ipv6_populate_dst_key(ctx->iph6, ctx->l4_proto, dst_key);
		*prot_net_map = SELECT_SHADOW_MAP(MAP_NET_IP6_BASENAME,
						   ctx->cfg->amap_prot_net);
		/* It is a regular case, don't need to add any statistic */
		return XFW_CTX_CONTINUE;
	}
	default:
		/* Let the kernel handle EtherTypes unknown to xFW. */
		return XFW_MAKE_CTX_PASS_EXT(ctx, XFW_L2_UNKNOWN_EGRESS,
					     ": %x", ctx->ipver);
	}
}

/**
 * Parsing function, should not drop packets!
 */
static __always_inline int
out_process_l4(XfwGlobalCtx *ctx, XfwDstKey *dst_key)
{
	switch (ctx->l4_proto) {
	case IPPROTO_TCP: {
		REG_PACKET_GLOBAL(ctx, XFW_TCP_TOTAL_EGRESS);
		if (unlikely(parse_tcphdr(&ctx->hdr_cur, &ctx->th) <= 0))
			return XFW_MAKE_CTX_PASS(ctx, XFW_TCP_BADHDR_EGRESS);

		dst_key->port = ctx->th->dest;
		/* It is a regular case, don't need to add any statistic */
		return XFW_CTX_CONTINUE;
	}
	case IPPROTO_UDP: {
		REG_PACKET_GLOBAL(ctx, XFW_UDP_TOTAL_EGRESS);
		if (unlikely(parse_udphdr(&ctx->hdr_cur, &ctx->uh) <= 0))
			return XFW_MAKE_CTX_PASS(ctx, XFW_UDP_BADHDR_EGRESS);

		dst_key->port = ctx->uh->dest;

		egress_dns_filter(ctx);

		/* It is a regular case, don't need to add any statistic */
		return XFW_CTX_CONTINUE;
	}
	default: {
		return XFW_MAKE_CTX_PASS_EXT(ctx, XFW_L4_UNSUPPORTED_EGRESS,
					     ": %u", ctx->l4_proto);
	}
	}
}

static __always_inline int
process_downstream_egress(const XfwGlobalCtx *ctx, const XfwDstKey *dst_key)
{
	/* Traffic still heading toward protected services must pass dst policy. */
	CHAIN(xfw_dst_filter, ctx, dst_key);

	return XFW_CTX_CONTINUE;
}

static __always_inline int
xfw_tc_egress_filter(struct XfwGlobalCtx *ctx, bool *is_upstream_egress)
{
	void *prot_net_map;
	XfwIpLpmKey prot_net_key;

	/* Filled by the parsing path that needs it. */
	XfwDstKey dst_key = {};

	XFW_DBG_INIT();

	/* We need to duplicate all parsing logic for xdp and tc hooks. Maybe later
	 * we will be able to use parsed context from the previous filter.
	 *
	 * This filter is is a filter that runs on traffic leaving the machine.
	 * It processes both traffic that has already been handled by xdp_*.c and
	 * traffic generated by the machine itself. If we cannot parse the packet
	 * to extract L3 or L4 data and continue processing it with the filter,
	 * then such a packet will be passed through without filtering (with
	 * TC_ACT_OK). However, we will still update the statistics so that we
	 * can monitor these packets.
	 *
	 * In general, a packet may fail to parse for different reasons. For example,
	 * it could have been generated locally by the machine itself, or it may
	 * have become corrupted while transitioning between network interfaces.
	 * In the latter case, we want visibility into the fact that such corruption
	 * is happening on the machine, which is why we collect statistics on these
	 * packets.
	 *
	 * If later we decide to block them, we will need to add the appropriate
	 * logic. For now, it seems that all such unusual packets will already be
	 * dropped by the xdp.c filter.
	 */

	ctx->ipver = parse_ethhdr(&ctx->hdr_cur, &ctx->eth);
	if (unlikely(ctx->ipver < 0))
		return XFW_MAKE_CTX_PASS(ctx, XFW_ETH_BADHDR_EGRESS);

	/* Build map lookup keys before policy evaluation. */
	CHAIN(out_process_l3, ctx, &dst_key, &prot_net_key, &prot_net_map);
	CHAIN(out_process_l4, ctx, &dst_key);
	/* Parsing is complete; start policy checks. */

	*is_upstream_egress = (bpf_map_lookup_elem(prot_net_map, &prot_net_key) == NULL);
	if (!*is_upstream_egress) /* Packets going to upstream. */
		CHAIN(process_downstream_egress, ctx, &dst_key);
	
	/* 
	 * Still needs to be called when rules are not loaded. TCP AUTH filter is
	 * atomatically inactive at that time.
	 */
	
	const XfwSockAddr sock_addr = {
		.addr = dst_key.addr,
		.port = dst_key.port
	};
	tcp_auth_conn_egress_learning(ctx, &sock_addr);

	return XFW_CTX_PASS;
}

/**
 * This program hooks into two types of packets: it can be attached to internal
 * and external interfaces and receive packets destined for the internal network
 * as well as other addresses. Here, `_egress` refers to the direction **from the
 * current machine (OUT)**. First, we perform common packet parsing, then we
 * consult the protected net map to determine the direction relative to our network:
 * whether the packet is going **TO** our protected network (**downstream**)
 * or **FROM** our protected network (**upstream**). Our network would be called
 * 'upstream network' or 'upstream server' for simplicity
 */
SEC("tc")
int
xfw_tc(struct __sk_buff *skb)
{
	XfwGlobalCtx ctx;
	xfw_ctx_init(&ctx, skb);
	XFW_ASSERT(ctx.cfg && ctx.g_stats);

	/*
	 * All parsing errors correspond to packets coming from the upstream server.
	 * Any malformed packets coming from the outer network side are already
	 * filtered by xdp.o. Therefore, if a parsing error occurs here, we can
	 * assume the traffic originates from the upstream server. (In practice,
	 * parsing errors are only possible in this direction, except when
	 * running in evaluation_mode.)
	 */
	bool is_upstream_egress = true;
	int res = xfw_tc_egress_filter(&ctx, &is_upstream_egress);

	if (is_upstream_egress) {
		/*
		 * Passed_upstream_egress will also include such passed trafic as
		 * preload_egress, eth_badhdr_egress, ip6_badhdr_egress,
		 * l2_unknown_egress, tcp_badhdr_egress, udp_badhdr_egress,
		 * l4_unsupported_egress. So if you want to have clear markers,
		 * it is better to remove these stats before calculation.
		 * All this trafic were passed before we even know is it upstream
		 * or downstream trafic.
		 */
		REG_PACKET_GLOBAL(&ctx, XFW_TOTAL_UPSTREAM_EGRESS);
		if (res == XFW_CTX_PASS)
			REG_PACKET_GLOBAL(&ctx, XFW_PASSED_UPSTREAM_EGRESS);
	} else {
		REG_PACKET_GLOBAL(&ctx, XFW_TOTAL_DOWNSTREAM_EGRESS);
		if (res == XFW_CTX_PASS)
			REG_PACKET_GLOBAL(&ctx, XFW_PASSED_DOWNSTREAM_EGRESS);
	}

	return finalize_result(&ctx, res);
}

/* TODO we should open source the code at some point. */
char LICENSE[] SEC("license") = "GPL v2";
