xfw {
	tcp_syncookies passive_timer=1 flood_timer=1;

	ratelimit=src_default_ratelimit pps=4294967295 bps=4294967295;
	defaults {
		src_ip ip4: ratelimit = src_default_ratelimit;
		src_ip ip6: ratelimit = src_default_ratelimit;
		src_port : ratelimit = src_default_ratelimit;

		dst: allow;
	}
}
