xfw {
	# Unlimited on 200Gbps NIC BPS and 100MPPS
	ratelimit=default_ratelimit bps=30000000000 pps=100000000;
	tcp_flags syn : ratelimit=default_ratelimit;

	defaults {
		src_ip ip4: allow;
		src_ip ip6: allow;
		src_port : allow;
		dst: allow;
	}
}
