xfw {
	# Almost unlimited BPS for 200Gbps NIC and very small limit for 10KRPS
	# to not to cause load onto the TCP/IP stack and benchmark xFW
	# filtration solely.
	ratelimit=default_ratelimit bps=30000000000 pps=10000;
	tcp_flags syn : ratelimit=default_ratelimit;

	defaults {
		src_ip ip4: allow;
		src_ip ip6: allow;
		src_port : allow;
		dst: allow;
	}
}
